---
namespace: "veeamhub"
name: "veeam"
version: "1.0.11"
readme: "readme_galaxy.md"
authors:
  - "Chris Arceneaux (https://www.arsano.ninja/)"
  - "Markus Kraus (https://mycloudrevolution.com/)"
description: Administer Veeam Software
license_file: "LICENSE"
tags:
  - veeam
  - availability
  - suite
  - backup
  - replication
  - enterprise
  - manager
  - one
  - server
  - system
  - backup
  - vbr
  - vem
  - em
repository: "https://github.com/VeeamHub/veeam-ansible"
issues: "https://github.com/VeeamHub/veeam-ansible/issues/new/choose"