---
namespace: "carceneaux"
name: "veeam"
version: "1.0.0"
readme: "readme_galaxy.md"
authors:
  - "Chris Arceneaux (https://www.arsano.ninja/)"
  - "Markus Kraus (https://mycloudrevolution.com/)"
description: Administer Veeam Software
license: GPL-3.0-only
license_file: "LICENSE"
tags:
  - veeam
  - veeam availability suite
  - veeam backup & replication
  - veeam backup enterprise manager
  - veeam one
  - veeam enterprise manager
  - enterprise manager
  - server
  - system
  - backup
repository: "https://github.com/VeeamHub/veeam-ansible"
issues: "https://github.com/VeeamHub/veeam-ansible/issues/new/choose"