---
# one_agent_upgrade tasks file for veeamhub.veeam_vas
- name: Checking to see if Veeam ONE Agent is installed
  veeam_software_check:
    name: "Veeam ONE Agent"
  register: software
- name: Is Veeam ONE Agent installed?
  fail:
    msg: "Veeam ONE Agent must be installed on this server in order to upgrade it."
  when: not (software.installed | bool)
- name: Is the correct version of Veeam ONE Agent installed?
  fail:
    msg: "You're trying to upgrade from an unsupported version. Please check Veeam documentation for more information: U(https://helpcenter.veeam.com/docs/one/deployment/upgrade.html?ver=100)"
  when:
    - software.version != '9.5.0.3801' # 9.5 U3
    - software.version != '9.5.4.4566' # 9.5 U4
    - software.version != '9.5.4.4587' # 9.5 U4a
- name: Including version-specific variables
  include_vars:
    file: "vars/one_v{{ version }}.yml"

# PRE-UPGRADE TASKS
- name: Veeam ONE ISO Tasks
  include_tasks: mount_iso.yml
- name: Print Installation Configuration
  debug:
    msg:
      - "Installation Source: '{{ source }}'"
      - "Installation Logs Folder: '{{ destination }}logs'"
      - "Version: {{ version }}"
      - "Download ISO?: {{ iso_download }}"
      - "ISO Source: {{ iso_url }}"
      - "ISO File Destination: {{ destination }}{{ destination_iso_file }}"
      - "Veeam ONE Service Account: {{ one_username | default('not specified') }}"
- name: Create logs directory
  win_file:
    path: "{{ destination }}logs"
    state: directory

# UPGRADING VEEAM SOFTWARE
- name: Upgrade ONE Agent Server
  win_package:
    path: "{{ source }}Agent\\VeeamONE.Agent.x64.msi"
    state: present
    arguments: '/L*v "{{ destination }}logs\\VeeamONE.Agent.x64.log" ACCEPT_THIRDPARTY_LICENSES=1 ACCEPT_EULA=1 VO_AGENT_SERVICE_ACCOUNT_NAME="{{ one_username }}" VO_AGENT_SERVICE_ACCOUNT_PASSWORD="{{ one_password }}"'
- name: Finding file(s) in '{{ source }}Updates' directory
  win_find:
    paths: "{{ source }}Updates"
    recurse: no
    file_type: file
  ignore_errors: yes
  register: file
- name: Does Veeam ONE need to be patched?
  set_fact:
    patch: "{{ not (file.failed) }}"
- name: Setting patch filename
  set_fact:
    patch_file: "{{ file.files[0].filename }}"
  when: patch | bool
- name: Including Veeam ONE patch tasks
  include_tasks: one_patch.yml
  when: patch | bool

# POST-UPGRADE TASKS
- name: Unmount ISO
  win_disk_image:
    image_path: "{{ destination }}{{ destination_iso_file }}"
    state: absent