---
# ONE v11 vars file for veeamhub.veeam_vas

## v10 vars
iso_url: "https://download2.veeam.com/VONE/v11/VeeamONE_11.0.0.1379_20210419.iso"
iso_checksum: "63c3591ca8a3585c597a6e39f3510c887c1034d7964b5972c52a5ed0bbd5476e"
destination_iso_file: "one.iso"
destination_license_file: "one-license.lic"
sql_express_file: "{{ source }}Redistr\\x64\\SqlExpress\\2016SP2\\SQLEXPR_x64_ENU.exe"
sql_database: "VeeamOne"
net_framework_file: "{{ source }}Redistr\\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"